gantt
todayMarker off
dateFormat YYYY
axisFormat %Y
title 人工智能的三次浪潮

section 史前文明

推理期: done, 1950, 1965
1950 图灵测试: 1950, milestone
1956 达特茅斯会议: 1956, milestone

知识期: done, 1969, 1987
1969 知识系统兴起: 1969, milestone
1980 专家系统兴起: 1980, milestone

学习期: active, 1985, 2021
1995 统计学习兴起: 1995, milestone
2012 深度学习兴起: 2012, milestone