gantt
todayMarker off
dateFormat  YYYY
axisFormat %Y

section 神经网络
模型提出: done, 1943, 1969
1943 MP神经网络: 1943, milestone
1958 Rosenblatt提出感知机: 1958, milestone
1969 Minsky出版《感知机》: 1969, milestone
冰河期: done, 1969, 1983
1974 反向传播被提出: 1974, milestone
1980 带卷积和子采样的新知机: 1980, milestone
复兴: done, 1983, 1995
1983 Hopfield网络: 1983, milestone
1984 Boltzmann机: 1984, milestone
1986 反向传播被重新提出: 1986, milestone
二次冰河: done, 1995, 2006
1995 统计机器学习兴起: 1995, milestone
深度学习: active, 2006, 2021
2012 DNN引起轰动: 2012, milestone